### ISSUE TITLE
Linking to coin-Clp

### ISSUE THREAD

**Issue by rsdenijs** [PetterS/submodular#1]
I downloaded and compiled the dev version of coin-Clp and linking gives me the following error

In my Cmakelists i have:

```
SET(COIN_LIB_DIR "/home/ubuntu/code/coin-Clp/lib" CACHE PATH "Coin (Clp, ...) library directory")
```

```
Linking CXX executable ../bin/submodular
/home/ubuntu/code/coin-Clp/lib/libCoinUtils.so: undefined reference to `gzopen'
...
```

What version of coin-Clp is compatible?

**Comment by PetterS** [comment]
`gzopen` is a function in zlib. You will have to link to zlib as well. 

Clp may have detected that zlib was installed and decided to use it. I have never had to use zlib on Windows.

I hope this helps.

**Comment by rsdenijs** [comment]
Thanks. I got It working, somehow. 
I also got the python wrapper to work on ubuntu. 
If you want, when I find some time to clean it up I can submit a pull request.

**Comment by PetterS** [comment]
The Python wrapper is even removed in the current master (due to me not finding the time to maintain it). I am surprised you found it.

Pull requests are always welcome. I’ll close this issue for now.

**Comment by rsdenijs** [comment]
I realized that I have the wrapper because I have an bit older checkout ;)

**Comment by cl3ar** [comment]
I'm having a similar issue. Not sure if this is the right place to comment...

Below is the call to the g++ and the return...
C:\C_Work2\test_CLP>g++ -Wall -fexceptions -g -IC:\lazy\Clp-1.15.10\Clp-1.15.10\
build\include\coin -IC:\lazy\zlib-1.2.3-src\src\zlib\1.2.3\zlib-1.2.3 -LC:\lazy\
Clp-1.15.10\Clp-1.15.10\build\lib\ -LC:\lazy\zlib-1.2.3-src\src\zlib\1.2.3\zlib-
1.2.3\ -o C:\C_Work2\test_CLP\bin\Debug\test_CLP.exe C:\C_Work2\test_CLP\main.cp
p -static C:\lazy\zlib-1.2.3-src\src\zlib\1.2.3\zlib-1.2.3\libz.a C:\lazy\Clp-1.
15.10\Clp-1.15.10\build\lib\libClp.a C:\lazy\Clp-1.15.10\Clp-1.15.10\build\lib\l
ibCoinUtils.a
C:\C_Work2\test_CLP\main.cpp: In function 'int main(int, const char**)':
C:\C_Work2\test_CLP\main.cpp:20:26: warning: unknown escape sequence: '\C' [enab
led by default]
     status=model.readMps("C:\C_Work2\test_CLP\p0033.mps");
                          ^
C:\C_Work2\test_CLP\main.cpp:20:26: warning: unknown escape sequence: '\p' [enab
led by default]
C:\lazy\Clp-1.15.10\Clp-1.15.10\build\lib\libCoinUtils.a(CoinFileIO.o):CoinFileI
O.cpp:(.text+0x64a): undefined reference to `gzopen'
C:\lazy\Clp-1.15.10\Clp-1.15.10\build\lib\libCoinUtils.a(CoinFileIO.o):CoinFileI
O.cpp:(.text+0xe21): undefined reference to`gzopen'
c:/c_work/compiler/gcc/bin/../lib/gcc/x86_64-w64-mingw32/4.8.1/../../../../x86_6
4-w64-mingw32/bin/ld.exe: C:\lazy\Clp-1.15.10\Clp-1.15.10\build\lib\libCoinUtils
.a(CoinFileIO.o): bad reloc address 0x0 in section `.pdata$_ZN21CoinGetslessFile
Input4getsEPci'
collect2.exe: error: ld returned 1 exit status

**Comment by cl3ar** [comment]
Would greatly appreciate if someone can give me any inputs. I have spent quite a lot of hours on this already. Also my command line compiler skills are somewhat limited!

Notes ...
1) I have a 64-bit windows machine
2) I built the zlib library from source files (that i downloaded and) using the configure & make scripts provided 
3) The CLP libraries were built from source files (that i downloaded and) using the configure & make scripts provided

**Comment by PetterS** [comment]
The first problem is:
   status=model.readMps("C:\C_Work2\test_CLP\p0033.mps");
Backslashes need to be escaped as \\ in C++ strings.

If ’gzopen’ is missing you need to link with zlib. The linker error suggest that you did not, even though you wrote that you built it. I recommend using Microsoft Visual Studio when building on Windows. There are free versions available.

**Comment by PetterS** [comment]
Note that issues with building Clp on various combinations of OSs and compilers are probably best answered by Coin. Once you example program is working building this library should be relatively easy.

**Comment by cl3ar** [comment]
Thank you for responding! I will try with MS VS. I think there are some Visual Studio solution files as part of the distribution, and those should allow me to circumvent the configure and make process.

**Comment by cl3ar** [comment]
I got it to work with g++. I was (previously) putting the reference to zlib (libz.a) in the wrong place. I'm including the compiler arguments (in the correct sequence) below for reference (i'm writing them out with new-lines only for readability - ofcourse these have to be removed before pasting to DOS)..

g++ 
-Wall 
-fexceptions 
-g 
-IC:\lazy\Clp-1.15.10\Clp-1.15.10\build\include\coin 
-IC:\lazy\zlib-1.2.3-src\src\zlib\1.2.3\zlib-1.2.3 
-LC:\lazy\Clp-1.15.10\Clp-1.15.10\build\lib\ 
-LC:\lazy\zlib-1.2.3-src\src\zlib\1.2.3\zlib-1.2.3\ 
-o C:\C_Work2\test_CLP\bin\Debug\test_CLP.exe 
C:\C_Work2\test_CLP\main.cpp 
-static 
C:\lazy\Clp-1.15.10\Clp-1.15.10\build\lib\libClp.a 
C:\lazy\Clp-1.15.10\Clp-1.15.10\build\lib\libCoinUtils.a 
C:\lazy\zlib-1.2.3-src\src\zlib\1.2.3\zlib-1.2.3\libz.a
